#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CORE="$ROOT/.agent/AGENT_RULES.md"

if [[ ! -f "$CORE" ]]; then
  echo "Missing canonical rules file: $CORE" >&2
  exit 1
fi

write_adapter() {
  local file="$1"
  local tool_name="$2"
  cat > "$ROOT/$file" <<ADAPTER
# ${tool_name} Adapter for MacWiki

> Auto-generated by \`scripts/sync-agent-entrypoints.sh\`.
> Edit canonical rules in \`.agent/AGENT_RULES.md\`, then re-run sync.

This file is a thin entrypoint for ${tool_name}.

## Canonical Instructions

1. Read \`.agent/AGENT_RULES.md\` (authoritative)
2. Run \`.agent/workflows/quickstart.md\` at session start
3. Run \`.agent/workflows/session-handoff.md\` at session end

If this file conflicts with \`.agent/AGENT_RULES.md\`, canonical rules win.

## Required Obsidian Context

Use Obsidian CLI as first entry point and target the correct vault:

\`obsidian vault="Jack" read path="Projects/MacWiki/MacWiki.md"\`

Then read the latest development log note in \`Projects/MacWiki/03 Development Log/\`.
ADAPTER
}

write_adapter "AGENTS.md" "Codex"
write_adapter "GEMINI.md" "Gemini"
write_adapter "CLAUDE.md" "Claude"
write_adapter "ANTIGRAVITY.md" "Antigravity"

echo "Synced agent adapters: AGENTS.md, GEMINI.md, CLAUDE.md, ANTIGRAVITY.md"
