#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CORE="$ROOT/.agent/AGENT_RULES.md"

if [[ ! -f "$CORE" ]]; then
  echo "Missing canonical rules file: $CORE" >&2
  exit 1
fi

write_adapter() {
  local file="$1"
  local tool_name="$2"
  cat > "$ROOT/$file" <<ADAPTER
# ${tool_name} Adapter for MacWiki

> Auto-generated by \`scripts/sync-agent-entrypoints.sh\`.
> Edit canonical rules in \`.agent/AGENT_RULES.md\`, then re-run sync.

This file is a thin entrypoint for ${tool_name}.

## Canonical Instructions

1. Read \`.agent/AGENT_RULES.md\` first. It is authoritative.
2. Use \`.agent/workflows/quickstart.md\` to decide how much context to load for this request.
3. Run \`.agent/workflows/commit-ready.md\` only when work is close to landing.
4. Run \`.agent/workflows/session-handoff.md\` only when the session is actually ending.

If this file conflicts with \`.agent/AGENT_RULES.md\`, canonical rules win.

## Context Policy

- Default to narrow startup: inspect the relevant code first.
- Read Jack \`Projects/MacWiki/MacWiki.md\` and Project Indy \`Projects/MacWiki/MacWiki Ops.md\` for resume work, ambiguous feature work, or project-state questions.
- Use Obsidian CLI first with \`vault="Jack"\` for product docs and \`vault="Project Indy"\` for operational/session docs. If the CLI bridge is disabled, fall back to direct vault file reads/patches.

## Additional Workflows

- \`.agent/workflows/build.md\` for build, run, and clean
- \`.agent/workflows/test.md\` for test execution
- \`.agent/workflows/code-review.md\` for review and self-review
ADAPTER
}

write_adapter "AGENTS.md" "Codex"
write_adapter "GEMINI.md" "Gemini"
write_adapter "CLAUDE.md" "Claude"
write_adapter "ANTIGRAVITY.md" "Antigravity"

echo "Synced agent adapters: AGENTS.md, GEMINI.md, CLAUDE.md, ANTIGRAVITY.md"
